-- =============================================================================
-- Aperture Energy Intelligence — Mart Views
-- Database: APERTURE_DB  |  Schema: ENERGY
-- Run as: SYSADMIN
--
-- Five mart views. Each reads from one fact table and may LEFT JOIN
-- dimensions that originate from the same data source (e.g. EIA dims
-- join EIA facts, GDELT dims join GDELT facts). No cross-source joins.
-- LEFT JOINs ensure no fact rows are lost on missing dimension keys.
--
--   1. MART_EIA_PRICES    — Daily national petroleum prices.
--                           Grain: PRICE_DATE.
--   2. MART_EIA_INVENTORY — Weekly petroleum inventory by PADD.
--                           Grain: REPORT_DATE × PADD_ID.
--   3. MART_EIA_STEO      — Monthly Short-Term Energy Outlook forecasts.
--                           Grain: FORECAST_MONTH.
--   4. MART_WEATHER       — NOAA temperature and degree days by PADD.
--                           Grain: OBSERVATION_DATE × PADD_ID.
--   5. MART_GEOPOLITICAL  — GDELT event scores by country.
--                           Grain: EVENT_DATE × COUNTRY_CODE.
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE APERTURE_DB;
USE SCHEMA ENERGY;

-- Drop legacy views
DROP VIEW IF EXISTS APERTURE_DB.ENERGY.MART_ENERGY_DAILY;
DROP VIEW IF EXISTS APERTURE_DB.ENERGY.MART_ENERGY;


-- =============================================================================
-- 1. MART_EIA_PRICES — Daily National Petroleum Prices
-- =============================================================================
-- Source: FACT_EIA_PRICES
-- Grain: PRICE_DATE (one row per trading day).

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_EIA_PRICES
  COMMENT = 'EIA daily national petroleum prices (WTI, Brent, gasoline, diesel, jet fuel). One row per trading day.'
AS
SELECT
    PRICE_DATE,
    DAYNAME(PRICE_DATE) AS DAY_OF_WEEK,
    WEEKOFYEAR(PRICE_DATE) AS WEEK_OF_YEAR,
    MONTH(PRICE_DATE) AS MONTH_NUM,
    MONTHNAME(PRICE_DATE) AS MONTH_NAME,
    QUARTER(PRICE_DATE) AS QUARTER_NUM,
    YEAR(PRICE_DATE) AS YEAR_NUM,

    MAX(CASE WHEN SERIES_ID = 'PET.RWTC.D' THEN PRICE_USD END) AS WTI_PRICE_USD,
    MAX(CASE WHEN SERIES_ID = 'PET.RBRTE.D' THEN PRICE_USD END) AS BRENT_PRICE_USD,
    MAX(CASE WHEN SERIES_ID = 'EMM_EPM0_PTE_NUS_DPG' THEN PRICE_USD END) AS GASOLINE_PRICE_USD,
    MAX(CASE WHEN SERIES_ID = 'PET.EER_EPJK_PF4_RGC_DPG.D' THEN PRICE_USD END) AS JET_FUEL_PRICE_USD,
    MAX(CASE WHEN SERIES_ID = 'EMD_EPD2DXL0_PTE_NUS_DPG' THEN PRICE_USD END) AS DIESEL_PRICE_USD,

    MAX(CASE WHEN SERIES_ID = 'PET.RWTC.D' THEN PRICE_USD END)
        - LAG(MAX(CASE WHEN SERIES_ID = 'PET.RWTC.D' THEN PRICE_USD END)) OVER (ORDER BY PRICE_DATE) AS WTI_DAILY_CHANGE,
    MAX(CASE WHEN SERIES_ID = 'PET.RBRTE.D' THEN PRICE_USD END)
        - MAX(CASE WHEN SERIES_ID = 'PET.RWTC.D' THEN PRICE_USD END) AS WTI_BRENT_SPREAD

FROM APERTURE_DB.ENERGY.FACT_EIA_PRICES
GROUP BY PRICE_DATE;


-- =============================================================================
-- 2. MART_EIA_INVENTORY — Weekly Petroleum Inventory by PADD
-- =============================================================================
-- Source: FACT_EIA_INVENTORY  LEFT JOIN  DIM_PADD_REGIONS (same EIA source)
-- Grain: REPORT_DATE × PADD_ID (one row per weekly report per PADD).

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_EIA_INVENTORY
  COMMENT = 'EIA weekly petroleum inventory by PADD with PADD dimension. One row per report date per PADD.'
AS
SELECT
    f.REPORT_DATE,
    DAYNAME(f.REPORT_DATE) AS DAY_OF_WEEK,
    WEEKOFYEAR(f.REPORT_DATE) AS WEEK_OF_YEAR,
    MONTH(f.REPORT_DATE) AS MONTH_NUM,
    MONTHNAME(f.REPORT_DATE) AS MONTH_NAME,
    QUARTER(f.REPORT_DATE) AS QUARTER_NUM,
    YEAR(f.REPORT_DATE) AS YEAR_NUM,

    f.PADD_ID,
    d.PADD_CODE,
    d.PADD_NAME,

    MAX(CASE WHEN f.SERIES_ID LIKE 'PET.WCEST%' THEN f.INVENTORY_THOUSAND_BARRELS END) AS CRUDE_INVENTORY_KBBL,
    MAX(CASE WHEN f.SERIES_ID LIKE 'PET.WCEST%' THEN f.WEEKLY_CHANGE_THOUSAND_BARRELS END) AS CRUDE_WEEKLY_CHANGE_KBBL,
    MAX(CASE WHEN f.SERIES_ID = 'PET.WTTSTUS1.W' THEN f.INVENTORY_THOUSAND_BARRELS END) AS TOTAL_PETROLEUM_INVENTORY_KBBL,
    MAX(CASE WHEN f.SERIES_ID = 'PET.WGTSTUS1.W' THEN f.INVENTORY_THOUSAND_BARRELS END) AS GASOLINE_INVENTORY_KBBL,
    MAX(CASE WHEN f.SERIES_ID = 'PET.WDISTUS1.W' THEN f.INVENTORY_THOUSAND_BARRELS END) AS DISTILLATE_INVENTORY_KBBL

FROM APERTURE_DB.ENERGY.FACT_EIA_INVENTORY f
LEFT JOIN APERTURE_DB.ENERGY.DIM_PADD_REGIONS d
    ON f.PADD_ID = d.PADD_ID
GROUP BY f.REPORT_DATE, f.PADD_ID, d.PADD_CODE, d.PADD_NAME;


-- =============================================================================
-- 3. MART_EIA_STEO — Monthly Short-Term Energy Outlook Forecasts
-- =============================================================================
-- Source: FACT_EIA_STEO_FORECASTS
-- Grain: FORECAST_MONTH (one row per month).

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_EIA_STEO
  COMMENT = 'EIA Short-Term Energy Outlook monthly forecasts. One row per forecast month.'
AS
SELECT
    FORECAST_MONTH,
    MONTHNAME(FORECAST_MONTH) AS MONTH_NAME,
    QUARTER(FORECAST_MONTH) AS QUARTER_NUM,
    YEAR(FORECAST_MONTH) AS YEAR_NUM,

    MAX(CASE WHEN SERIES_ID = 'STEO.BREPUUS.M' THEN FORECAST_VALUE END) AS STEO_WTI_FORECAST,
    MAX(CASE WHEN SERIES_ID = 'STEO.BRIPUUS.M' THEN FORECAST_VALUE END) AS STEO_BRENT_FORECAST,
    MAX(CASE WHEN SERIES_ID = 'STEO.COPRPUS.M' THEN FORECAST_VALUE END) AS STEO_PRODUCTION_FORECAST,
    MAX(CASE WHEN SERIES_ID = 'STEO.PAPRPUS.M' THEN FORECAST_VALUE END) AS STEO_CONSUMPTION_FORECAST,
    MAX(CASE WHEN SERIES_ID = 'STEO.MGEIAUS.M' THEN FORECAST_VALUE END) AS STEO_GASOLINE_PRICE_FORECAST,
    MAX(CASE WHEN SERIES_ID = 'STEO.D2RCAUS.M' THEN FORECAST_VALUE END) AS STEO_DIESEL_PRICE_FORECAST,
    MAX(PUBLICATION_DATE) AS STEO_PUBLICATION_DATE

FROM APERTURE_DB.ENERGY.FACT_EIA_STEO_FORECASTS
GROUP BY FORECAST_MONTH;


-- =============================================================================
-- 4. MART_WEATHER — NOAA Temperature and Degree Days by PADD
-- =============================================================================
-- Source: FACT_NOAA_WEATHER
-- Grain: OBSERVATION_DATE × PADD_ID (daily, PADDs 1-5).

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_WEATHER
  COMMENT = 'NOAA daily temperature and degree-day data by PADD. Fact data only.'
AS
SELECT
    OBSERVATION_DATE,
    DAYNAME(OBSERVATION_DATE) AS DAY_OF_WEEK,
    WEEKOFYEAR(OBSERVATION_DATE) AS WEEK_OF_YEAR,
    MONTH(OBSERVATION_DATE) AS MONTH_NUM,
    MONTHNAME(OBSERVATION_DATE) AS MONTH_NAME,
    QUARTER(OBSERVATION_DATE) AS QUARTER_NUM,
    YEAR(OBSERVATION_DATE) AS YEAR_NUM,

    PADD_ID,

    AVG_TEMP_F,
    MIN_TEMP_F,
    MAX_TEMP_F,
    HEATING_DEGREE_DAYS,
    COOLING_DEGREE_DAYS,
    STATION_COUNT AS WEATHER_STATION_COUNT

FROM APERTURE_DB.ENERGY.FACT_NOAA_WEATHER;


-- =============================================================================
-- 5. MART_GEOPOLITICAL — GDELT Event Scores by Country
-- =============================================================================
-- Source: FACT_GDELT_EVENTS  LEFT JOIN  DIM_GDELT_COUNTRY_PADD_MAP (same GDELT source)
-- Grain: EVENT_DATE × COUNTRY_CODE (weekly, per country).

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_GEOPOLITICAL
  COMMENT = 'GDELT weekly geopolitical event scores by country with country dimension. Fact data only.'
AS
SELECT
    f.EVENT_DATE,
    DAYNAME(f.EVENT_DATE) AS DAY_OF_WEEK,
    WEEKOFYEAR(f.EVENT_DATE) AS WEEK_OF_YEAR,
    MONTH(f.EVENT_DATE) AS MONTH_NUM,
    MONTHNAME(f.EVENT_DATE) AS MONTH_NAME,
    QUARTER(f.EVENT_DATE) AS QUARTER_NUM,
    YEAR(f.EVENT_DATE) AS YEAR_NUM,

    f.COUNTRY_CODE,
    f.COUNTRY_NAME,
    f.PRIMARY_PADD_IMPACT,
    d.ENERGY_RELEVANCE,
    d.DESCRIPTION AS COUNTRY_DESCRIPTION,

    f.AVG_TONE,
    f.AVG_GOLDSTEIN_SCALE,
    f.EVENT_COUNT,
    f.CONFLICT_EVENT_COUNT,
    f.COOPERATION_EVENT_COUNT,
    f.GEOPOLITICAL_TENSION_SCORE

FROM APERTURE_DB.ENERGY.FACT_GDELT_EVENTS f
LEFT JOIN APERTURE_DB.ENERGY.DIM_GDELT_COUNTRY_PADD_MAP d
    ON f.COUNTRY_CODE = d.COUNTRY_CODE;
