-- =============================================================================
-- Aperture Energy Intelligence — MART_ENERGY_DAILY View
-- Database: APERTURE_DB  |  Schema: ENERGY
-- Run as: SYSADMIN
--
-- Denormalized view joining all 4 sources by date + PADD region.
-- Primary datasource for Tableau Cloud live connection via VizQL Data Service.
-- 50 columns covering prices, inventory, weather, geopolitics, and forecasts.
--
-- Usage in Tableau:
--   SELECT * FROM APERTURE_DB.ENERGY.MART_ENERGY_DAILY
--   WHERE PADD_ID = 3 AND CALENDAR_DATE >= '2024-01-01'
--   ORDER BY CALENDAR_DATE DESC LIMIT 500;
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE APERTURE_DB;
USE SCHEMA ENERGY;

CREATE OR REPLACE VIEW APERTURE_DB.ENERGY.MART_ENERGY_DAILY
  COMMENT = 'Denormalized mart joining EIA prices, inventory, NOAA weather, GDELT events, and STEO forecasts by date and PADD region. Primary datasource for Tableau Cloud.'
AS
WITH date_spine AS (
    -- 3+ years of daily dates to match backfill window
    SELECT DATEADD(DAY, SEQ4(), DATEADD(YEAR, -3, CURRENT_DATE())) AS CALENDAR_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 1200))
    WHERE CALENDAR_DATE <= CURRENT_DATE()
),
padds AS (
    SELECT PADD_ID, PADD_CODE, PADD_NAME, PADD_DESCRIPTION,
           CENTROID_LAT, CENTROID_LON
    FROM APERTURE_DB.ENERGY.DIM_PADD_REGIONS
),
-- Pivot daily prices: WTI, Brent, Gasoline, Jet Fuel, Diesel
prices AS (
    SELECT
        PRICE_DATE,
        MAX(CASE WHEN SERIES_ID = 'PET.RWTC.D' THEN PRICE_USD END) AS WTI_PRICE_USD,
        MAX(CASE WHEN SERIES_ID = 'PET.RBRTE.D' THEN PRICE_USD END) AS BRENT_PRICE_USD,
        MAX(CASE WHEN SERIES_ID = 'PET.EMM_EPMR_PTE_NUS_DPG.D' THEN PRICE_USD END) AS GASOLINE_PRICE_USD,
        MAX(CASE WHEN SERIES_ID = 'PET.EER_EPJK_PF4_RGC_DPG.D' THEN PRICE_USD END) AS JET_FUEL_PRICE_USD,
        MAX(CASE WHEN SERIES_ID = 'PET.EER_EPD2F_PF4_RGC_DPG.D' THEN PRICE_USD END) AS DIESEL_PRICE_USD
    FROM APERTURE_DB.ENERGY.FACT_EIA_PRICES
    GROUP BY PRICE_DATE
),
-- Pivot weekly inventory by product type, grouped by PADD
inventory AS (
    SELECT
        REPORT_DATE,
        PADD_ID,
        MAX(CASE WHEN SERIES_ID LIKE 'PET.WCEST%' THEN INVENTORY_THOUSAND_BARRELS END) AS CRUDE_INVENTORY_KBBL,
        MAX(CASE WHEN SERIES_ID LIKE 'PET.WCEST%' THEN WEEKLY_CHANGE_THOUSAND_BARRELS END) AS CRUDE_WEEKLY_CHANGE_KBBL,
        MAX(CASE WHEN SERIES_ID = 'PET.WTTSTUS1.W' THEN INVENTORY_THOUSAND_BARRELS END) AS TOTAL_PETROLEUM_INVENTORY_KBBL,
        MAX(CASE WHEN SERIES_ID = 'PET.WGTSTUS1.W' THEN INVENTORY_THOUSAND_BARRELS END) AS GASOLINE_INVENTORY_KBBL,
        MAX(CASE WHEN SERIES_ID = 'PET.WDISTUS1.W' THEN INVENTORY_THOUSAND_BARRELS END) AS DISTILLATE_INVENTORY_KBBL
    FROM APERTURE_DB.ENERGY.FACT_EIA_INVENTORY
    GROUP BY REPORT_DATE, PADD_ID
),
-- Aggregate GDELT country-level events to PADD level
gdelt_by_padd AS (
    SELECT
        g.EVENT_DATE,
        g.PRIMARY_PADD_IMPACT AS PADD_ID,
        ROUND(AVG(g.AVG_TONE), 3) AS GEOPOLITICAL_AVG_TONE,
        ROUND(AVG(g.GEOPOLITICAL_TENSION_SCORE), 2) AS GEOPOLITICAL_TENSION_SCORE,
        SUM(g.EVENT_COUNT) AS GEOPOLITICAL_EVENT_COUNT,
        SUM(g.CONFLICT_EVENT_COUNT) AS GEOPOLITICAL_CONFLICT_COUNT,
        SUM(g.COOPERATION_EVENT_COUNT) AS GEOPOLITICAL_COOPERATION_COUNT
    FROM APERTURE_DB.ENERGY.FACT_GDELT_EVENTS g
    WHERE g.PRIMARY_PADD_IMPACT IS NOT NULL
    GROUP BY g.EVENT_DATE, g.PRIMARY_PADD_IMPACT
),
-- Pivot monthly STEO forecasts to key metrics
steo AS (
    SELECT
        FORECAST_MONTH,
        MAX(CASE WHEN SERIES_ID = 'STEO.BREPUUS.M' THEN FORECAST_VALUE END) AS STEO_WTI_FORECAST,
        MAX(CASE WHEN SERIES_ID = 'STEO.BRIPUUS.M' THEN FORECAST_VALUE END) AS STEO_BRENT_FORECAST,
        MAX(CASE WHEN SERIES_ID = 'STEO.COPRPUS.M' THEN FORECAST_VALUE END) AS STEO_PRODUCTION_FORECAST,
        MAX(CASE WHEN SERIES_ID = 'STEO.PAPRPUS.M' THEN FORECAST_VALUE END) AS STEO_CONSUMPTION_FORECAST,
        MAX(CASE WHEN SERIES_ID = 'STEO.MGEIAUS.M' THEN FORECAST_VALUE END) AS STEO_GASOLINE_PRICE_FORECAST,
        MAX(CASE WHEN SERIES_ID = 'STEO.D2RCAUS.M' THEN FORECAST_VALUE END) AS STEO_DIESEL_PRICE_FORECAST,
        MAX(PUBLICATION_DATE) AS STEO_PUBLICATION_DATE
    FROM APERTURE_DB.ENERGY.FACT_EIA_STEO_FORECASTS
    GROUP BY FORECAST_MONTH
)
SELECT
    -- ── Date dimension ──
    ds.CALENDAR_DATE,
    DAYNAME(ds.CALENDAR_DATE) AS DAY_OF_WEEK,
    WEEKOFYEAR(ds.CALENDAR_DATE) AS WEEK_OF_YEAR,
    MONTH(ds.CALENDAR_DATE) AS MONTH_NUM,
    MONTHNAME(ds.CALENDAR_DATE) AS MONTH_NAME,
    QUARTER(ds.CALENDAR_DATE) AS QUARTER_NUM,
    YEAR(ds.CALENDAR_DATE) AS YEAR_NUM,

    -- ── PADD region dimension ──
    p.PADD_ID,
    p.PADD_CODE,
    p.PADD_NAME,
    p.PADD_DESCRIPTION,
    p.CENTROID_LAT,
    p.CENTROID_LON,

    -- ── EIA Prices (national, same across all PADDs) ──
    pr.WTI_PRICE_USD,
    pr.BRENT_PRICE_USD,
    pr.GASOLINE_PRICE_USD,
    pr.JET_FUEL_PRICE_USD,
    pr.DIESEL_PRICE_USD,
    pr.WTI_PRICE_USD - LAG(pr.WTI_PRICE_USD) OVER (PARTITION BY p.PADD_ID ORDER BY ds.CALENDAR_DATE) AS WTI_DAILY_CHANGE,
    pr.BRENT_PRICE_USD - pr.WTI_PRICE_USD AS WTI_BRENT_SPREAD,

    -- ── EIA Inventory (PADD-specific where available) ──
    inv.CRUDE_INVENTORY_KBBL,
    inv.CRUDE_WEEKLY_CHANGE_KBBL,
    inv.TOTAL_PETROLEUM_INVENTORY_KBBL,
    inv.GASOLINE_INVENTORY_KBBL,
    inv.DISTILLATE_INVENTORY_KBBL,

    -- ── NOAA Weather (PADD-specific daily) ──
    w.AVG_TEMP_F,
    w.MIN_TEMP_F,
    w.MAX_TEMP_F,
    w.HEATING_DEGREE_DAYS,
    w.COOLING_DEGREE_DAYS,
    w.STATION_COUNT AS WEATHER_STATION_COUNT,

    -- ── GDELT Geopolitical (PADD-specific weekly) ──
    gp.GEOPOLITICAL_AVG_TONE,
    gp.GEOPOLITICAL_TENSION_SCORE,
    gp.GEOPOLITICAL_EVENT_COUNT,
    gp.GEOPOLITICAL_CONFLICT_COUNT,
    gp.GEOPOLITICAL_COOPERATION_COUNT,

    -- ── EIA STEO Forecasts (monthly grain, joined by month) ──
    st.STEO_WTI_FORECAST,
    st.STEO_BRENT_FORECAST,
    st.STEO_PRODUCTION_FORECAST,
    st.STEO_CONSUMPTION_FORECAST,
    st.STEO_GASOLINE_PRICE_FORECAST,
    st.STEO_DIESEL_PRICE_FORECAST,
    st.STEO_PUBLICATION_DATE,

    -- ── Derived: Forecast vs Actual ──
    CASE WHEN pr.WTI_PRICE_USD IS NOT NULL AND st.STEO_WTI_FORECAST IS NOT NULL
         THEN ROUND(pr.WTI_PRICE_USD - st.STEO_WTI_FORECAST, 2) END AS WTI_FORECAST_DIVERGENCE,
    CASE WHEN pr.BRENT_PRICE_USD IS NOT NULL AND st.STEO_BRENT_FORECAST IS NOT NULL
         THEN ROUND(pr.BRENT_PRICE_USD - st.STEO_BRENT_FORECAST, 2) END AS BRENT_FORECAST_DIVERGENCE,

    -- ── Data completeness flags (for Tableau conditional formatting) ──
    IFF(pr.WTI_PRICE_USD IS NOT NULL, TRUE, FALSE) AS HAS_PRICE_DATA,
    IFF(inv.CRUDE_INVENTORY_KBBL IS NOT NULL, TRUE, FALSE) AS HAS_INVENTORY_DATA,
    IFF(w.AVG_TEMP_F IS NOT NULL, TRUE, FALSE) AS HAS_WEATHER_DATA,
    IFF(gp.GEOPOLITICAL_TENSION_SCORE IS NOT NULL, TRUE, FALSE) AS HAS_GEOPOLITICAL_DATA,
    IFF(st.STEO_WTI_FORECAST IS NOT NULL, TRUE, FALSE) AS HAS_FORECAST_DATA

FROM date_spine ds
CROSS JOIN padds p
LEFT JOIN prices pr
    ON ds.CALENDAR_DATE = pr.PRICE_DATE
LEFT JOIN inventory inv
    ON ds.CALENDAR_DATE = inv.REPORT_DATE AND p.PADD_ID = inv.PADD_ID
LEFT JOIN APERTURE_DB.ENERGY.FACT_NOAA_WEATHER w
    ON ds.CALENDAR_DATE = w.OBSERVATION_DATE AND p.PADD_ID = w.PADD_ID
LEFT JOIN gdelt_by_padd gp
    ON ds.CALENDAR_DATE = gp.EVENT_DATE AND p.PADD_ID = gp.PADD_ID
LEFT JOIN steo st
    ON DATE_TRUNC('MONTH', ds.CALENDAR_DATE) = st.FORECAST_MONTH;
