-- =============================================================================
-- Aperture Energy Intelligence — Validation Queries
-- Database: APERTURE_DB  |  Schema: ENERGY
-- Run as: SYSADMIN
--
-- Section 1: Structural validation (run immediately after DDL)
-- Section 2: Data quality checks (run after backfill procedures)
-- Section 3: Mart view sample queries (Tableau-style VizQL patterns)
-- Section 4: Pipeline monitoring queries
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE APERTURE_DB;
USE SCHEMA ENERGY;

-- =============================================================================
-- SECTION 1: STRUCTURAL VALIDATION (can run immediately)
-- =============================================================================

-- 1.1  Table row counts — dimensions should match expected, facts empty pre-backfill
SELECT 'DIM_PADD_REGIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 6 AS EXPECTED,
       IFF(COUNT(*) = 6, 'PASS', 'FAIL') AS STATUS
FROM APERTURE_DB.ENERGY.DIM_PADD_REGIONS
UNION ALL
SELECT 'DIM_NOAA_STATION_PADD_MAP', COUNT(*), 51,
       IFF(COUNT(*) = 51, 'PASS', 'FAIL')
FROM APERTURE_DB.ENERGY.DIM_NOAA_STATION_PADD_MAP
UNION ALL
SELECT 'DIM_GDELT_COUNTRY_PADD_MAP', COUNT(*), 20,
       IFF(COUNT(*) = 20, 'PASS', 'FAIL')
FROM APERTURE_DB.ENERGY.DIM_GDELT_COUNTRY_PADD_MAP;

-- 1.2  PADD referential integrity — all station mappings point to valid PADDs
SELECT 'Station→PADD FK' AS VALIDATION,
       COUNT(*) AS TOTAL_STATIONS,
       SUM(CASE WHEN p.PADD_ID IS NULL THEN 1 ELSE 0 END) AS ORPHANED,
       IFF(SUM(CASE WHEN p.PADD_ID IS NULL THEN 1 ELSE 0 END) = 0, 'PASS', 'FAIL') AS STATUS
FROM APERTURE_DB.ENERGY.DIM_NOAA_STATION_PADD_MAP s
LEFT JOIN APERTURE_DB.ENERGY.DIM_PADD_REGIONS p ON s.PADD_ID = p.PADD_ID;

-- 1.3  GDELT country referential integrity
SELECT 'Country→PADD FK' AS VALIDATION,
       COUNT(*) AS TOTAL_COUNTRIES,
       SUM(CASE WHEN p.PADD_ID IS NULL THEN 1 ELSE 0 END) AS ORPHANED,
       IFF(SUM(CASE WHEN p.PADD_ID IS NULL THEN 1 ELSE 0 END) = 0, 'PASS', 'FAIL') AS STATUS
FROM APERTURE_DB.ENERGY.DIM_GDELT_COUNTRY_PADD_MAP g
LEFT JOIN APERTURE_DB.ENERGY.DIM_PADD_REGIONS p ON g.PRIMARY_PADD_IMPACT = p.PADD_ID;

-- 1.4  Station distribution across PADDs (expect coverage of PADDs 1-5)
SELECT p.PADD_CODE, p.PADD_NAME, COUNT(s.NOAA_STATION_ID) AS STATION_COUNT
FROM APERTURE_DB.ENERGY.DIM_PADD_REGIONS p
LEFT JOIN APERTURE_DB.ENERGY.DIM_NOAA_STATION_PADD_MAP s ON p.PADD_ID = s.PADD_ID
GROUP BY p.PADD_ID, p.PADD_CODE, p.PADD_NAME
ORDER BY p.PADD_ID;

-- 1.5  Stored procedures exist (expect 5+)
SELECT PROCEDURE_NAME, PROCEDURE_LANGUAGE
FROM APERTURE_DB.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'ENERGY' AND PROCEDURE_NAME LIKE 'SP_BACKFILL%'
ORDER BY PROCEDURE_NAME;

-- 1.6  Tasks exist with correct states
SHOW TASKS IN SCHEMA APERTURE_DB.ENERGY;

-- 1.7  Mart view column counts (5 independent marts)
SELECT TABLE_NAME, COUNT(*) AS COLUMN_COUNT,
       CASE TABLE_NAME
           WHEN 'MART_EIA_PRICES'    THEN IFF(COUNT(*) = 14, 'PASS', 'FAIL')
           WHEN 'MART_EIA_INVENTORY' THEN IFF(COUNT(*) = 15, 'PASS', 'FAIL')
           WHEN 'MART_EIA_STEO'      THEN IFF(COUNT(*) = 11, 'PASS', 'FAIL')
           WHEN 'MART_WEATHER'       THEN IFF(COUNT(*) = 14, 'PASS', 'FAIL')
           WHEN 'MART_GEOPOLITICAL'  THEN IFF(COUNT(*) = 18, 'PASS', 'FAIL')
       END AS STATUS
FROM APERTURE_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ENERGY'
  AND TABLE_NAME IN ('MART_EIA_PRICES', 'MART_EIA_INVENTORY', 'MART_EIA_STEO', 'MART_WEATHER', 'MART_GEOPOLITICAL')
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- 1.8  Mart view coverage (each mart has its own natural grain)
SELECT 'MART_EIA_PRICES' AS VIEW_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PRICE_DATE) AS DISTINCT_KEYS,
    MIN(PRICE_DATE) AS MIN_DATE,
    MAX(PRICE_DATE) AS MAX_DATE
FROM APERTURE_DB.ENERGY.MART_EIA_PRICES
UNION ALL
SELECT 'MART_EIA_INVENTORY',
    COUNT(*), COUNT(DISTINCT REPORT_DATE || '-' || PADD_ID),
    MIN(REPORT_DATE), MAX(REPORT_DATE)
FROM APERTURE_DB.ENERGY.MART_EIA_INVENTORY
UNION ALL
SELECT 'MART_EIA_STEO',
    COUNT(*), COUNT(DISTINCT FORECAST_MONTH),
    MIN(FORECAST_MONTH), MAX(FORECAST_MONTH)
FROM APERTURE_DB.ENERGY.MART_EIA_STEO
UNION ALL
SELECT 'MART_WEATHER',
    COUNT(*), COUNT(DISTINCT OBSERVATION_DATE || '-' || PADD_ID),
    MIN(OBSERVATION_DATE), MAX(OBSERVATION_DATE)
FROM APERTURE_DB.ENERGY.MART_WEATHER
UNION ALL
SELECT 'MART_GEOPOLITICAL',
    COUNT(*), COUNT(DISTINCT EVENT_DATE || '-' || COUNTRY_CODE),
    MIN(EVENT_DATE), MAX(EVENT_DATE)
FROM APERTURE_DB.ENERGY.MART_GEOPOLITICAL;

-- 1.9  Role grants — TABLEAU_READER_ROLE should have SELECT on all mart views
SHOW GRANTS ON VIEW APERTURE_DB.ENERGY.MART_EIA_PRICES;
SHOW GRANTS ON VIEW APERTURE_DB.ENERGY.MART_EIA_INVENTORY;
SHOW GRANTS ON VIEW APERTURE_DB.ENERGY.MART_EIA_STEO;
SHOW GRANTS ON VIEW APERTURE_DB.ENERGY.MART_WEATHER;
SHOW GRANTS ON VIEW APERTURE_DB.ENERGY.MART_GEOPOLITICAL;


-- =============================================================================
-- SECTION 2: DATA QUALITY CHECKS (run after backfill with real API keys)
-- =============================================================================

-- 2.1  EIA Prices — expect ~750 trading days/3yrs, 5 distinct series
SELECT
    'FACT_EIA_PRICES' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT SERIES_ID) AS DISTINCT_SERIES,
    COUNT(DISTINCT PRICE_DATE) AS DISTINCT_DATES,
    MIN(PRICE_DATE) AS MIN_DATE,
    MAX(PRICE_DATE) AS MAX_DATE,
    ROUND(AVG(PRICE_USD), 2) AS AVG_PRICE,
    SUM(CASE WHEN PRICE_USD IS NULL OR PRICE_USD <= 0 THEN 1 ELSE 0 END) AS INVALID_PRICES
FROM APERTURE_DB.ENERGY.FACT_EIA_PRICES;

-- 2.2  EIA Prices — per-series coverage check
SELECT
    SERIES_ID,
    COUNT(*) AS ROW_COUNT,
    MIN(PRICE_DATE) AS MIN_DATE,
    MAX(PRICE_DATE) AS MAX_DATE,
    ROUND(MIN(PRICE_USD), 2) AS MIN_PRICE,
    ROUND(MAX(PRICE_USD), 2) AS MAX_PRICE,
    ROUND(AVG(PRICE_USD), 2) AS AVG_PRICE
FROM APERTURE_DB.ENERGY.FACT_EIA_PRICES
GROUP BY SERIES_ID
ORDER BY SERIES_ID;

-- 2.3  EIA Inventory — expect weekly data, 6 PADDs, multiple product series
SELECT
    'FACT_EIA_INVENTORY' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT SERIES_ID) AS DISTINCT_SERIES,
    COUNT(DISTINCT PADD_ID) AS DISTINCT_PADDS,
    COUNT(DISTINCT REPORT_DATE) AS DISTINCT_DATES,
    MIN(REPORT_DATE) AS MIN_DATE,
    MAX(REPORT_DATE) AS MAX_DATE,
    SUM(CASE WHEN INVENTORY_THOUSAND_BARRELS IS NULL THEN 1 ELSE 0 END) AS NULL_INVENTORY
FROM APERTURE_DB.ENERGY.FACT_EIA_INVENTORY;

-- 2.4  EIA Inventory — per-PADD breakdown
SELECT
    p.PADD_CODE,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT i.SERIES_ID) AS SERIES_COUNT,
    MIN(i.REPORT_DATE) AS MIN_DATE,
    MAX(i.REPORT_DATE) AS MAX_DATE
FROM APERTURE_DB.ENERGY.FACT_EIA_INVENTORY i
JOIN APERTURE_DB.ENERGY.DIM_PADD_REGIONS p ON i.PADD_ID = p.PADD_ID
GROUP BY p.PADD_CODE
ORDER BY p.PADD_CODE;

-- 2.5  NOAA Weather — expect daily data, 5 PADDs (no US total)
SELECT
    'FACT_NOAA_WEATHER' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PADD_ID) AS DISTINCT_PADDS,
    COUNT(DISTINCT OBSERVATION_DATE) AS DISTINCT_DATES,
    MIN(OBSERVATION_DATE) AS MIN_DATE,
    MAX(OBSERVATION_DATE) AS MAX_DATE,
    ROUND(AVG(AVG_TEMP_F), 1) AS OVERALL_AVG_TEMP,
    SUM(CASE WHEN AVG_TEMP_F < -50 OR AVG_TEMP_F > 130 THEN 1 ELSE 0 END) AS OUTLIER_TEMPS
FROM APERTURE_DB.ENERGY.FACT_NOAA_WEATHER;

-- 2.6  NOAA Weather — HDD/CDD sanity check (should be non-negative, sum > 0)
SELECT
    p.PADD_CODE,
    COUNT(*) AS OBSERVATIONS,
    ROUND(AVG(w.HEATING_DEGREE_DAYS), 2) AS AVG_HDD,
    ROUND(AVG(w.COOLING_DEGREE_DAYS), 2) AS AVG_CDD,
    SUM(CASE WHEN w.HEATING_DEGREE_DAYS < 0 THEN 1 ELSE 0 END) AS NEGATIVE_HDD,
    SUM(CASE WHEN w.COOLING_DEGREE_DAYS < 0 THEN 1 ELSE 0 END) AS NEGATIVE_CDD
FROM APERTURE_DB.ENERGY.FACT_NOAA_WEATHER w
JOIN APERTURE_DB.ENERGY.DIM_PADD_REGIONS p ON w.PADD_ID = p.PADD_ID
GROUP BY p.PADD_CODE
ORDER BY p.PADD_CODE;

-- 2.7  GDELT Events — expect weekly data, 20 countries, tension 0-10
SELECT
    'FACT_GDELT_EVENTS' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT COUNTRY_CODE) AS DISTINCT_COUNTRIES,
    COUNT(DISTINCT EVENT_DATE) AS DISTINCT_DATES,
    MIN(EVENT_DATE) AS MIN_DATE,
    MAX(EVENT_DATE) AS MAX_DATE,
    ROUND(AVG(GEOPOLITICAL_TENSION_SCORE), 2) AS AVG_TENSION,
    SUM(CASE WHEN GEOPOLITICAL_TENSION_SCORE < 0 OR GEOPOLITICAL_TENSION_SCORE > 10 THEN 1 ELSE 0 END) AS OUT_OF_RANGE
FROM APERTURE_DB.ENERGY.FACT_GDELT_EVENTS;

-- 2.8  GDELT — country distribution and PADD mapping coverage
SELECT
    g.COUNTRY_CODE,
    m.COUNTRY_NAME,
    m.PRIMARY_PADD_IMPACT,
    COUNT(*) AS EVENT_ROWS,
    ROUND(AVG(g.GEOPOLITICAL_TENSION_SCORE), 2) AS AVG_TENSION
FROM APERTURE_DB.ENERGY.FACT_GDELT_EVENTS g
LEFT JOIN APERTURE_DB.ENERGY.DIM_GDELT_COUNTRY_PADD_MAP m ON g.COUNTRY_CODE = m.COUNTRY_CODE
GROUP BY g.COUNTRY_CODE, m.COUNTRY_NAME, m.PRIMARY_PADD_IMPACT
ORDER BY EVENT_ROWS DESC;

-- 2.9  EIA STEO Forecasts — expect monthly data, 9 series
SELECT
    'FACT_EIA_STEO_FORECASTS' AS TABLE_NAME,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT SERIES_ID) AS DISTINCT_SERIES,
    COUNT(DISTINCT FORECAST_MONTH) AS DISTINCT_MONTHS,
    MIN(FORECAST_MONTH) AS MIN_MONTH,
    MAX(FORECAST_MONTH) AS MAX_MONTH,
    SUM(CASE WHEN FORECAST_VALUE IS NULL THEN 1 ELSE 0 END) AS NULL_FORECASTS
FROM APERTURE_DB.ENERGY.FACT_EIA_STEO_FORECASTS;

-- 2.10 STEO — per-series breakdown
SELECT
    SERIES_ID,
    COUNT(*) AS ROW_COUNT,
    MIN(FORECAST_MONTH) AS MIN_MONTH,
    MAX(FORECAST_MONTH) AS MAX_MONTH,
    ROUND(MIN(FORECAST_VALUE), 2) AS MIN_VALUE,
    ROUND(MAX(FORECAST_VALUE), 2) AS MAX_VALUE
FROM APERTURE_DB.ENERGY.FACT_EIA_STEO_FORECASTS
GROUP BY SERIES_ID
ORDER BY SERIES_ID;


-- =============================================================================
-- SECTION 3: MART VIEW SAMPLE QUERIES (Tableau VizQL patterns)
-- =============================================================================

-- 3.1  WTI Price trend (last 90 days)
SELECT PRICE_DATE, WTI_PRICE_USD, WTI_DAILY_CHANGE, WTI_BRENT_SPREAD
FROM APERTURE_DB.ENERGY.MART_EIA_PRICES
WHERE PRICE_DATE >= DATEADD(DAY, -90, CURRENT_DATE())
ORDER BY PRICE_DATE DESC
LIMIT 500;

-- 3.2  Inventory by PADD (latest 12 weeks)
SELECT REPORT_DATE, PADD_CODE, PADD_NAME,
       CRUDE_INVENTORY_KBBL, CRUDE_WEEKLY_CHANGE_KBBL,
       TOTAL_PETROLEUM_INVENTORY_KBBL
FROM APERTURE_DB.ENERGY.MART_EIA_INVENTORY
WHERE PADD_ID IN (1,2,3,4,5)
  AND REPORT_DATE >= DATEADD(WEEK, -12, CURRENT_DATE())
ORDER BY REPORT_DATE DESC, PADD_ID
LIMIT 500;

-- 3.3  Heating Degree Days (PADD 1 + PADD 2, last winter)
SELECT OBSERVATION_DATE, PADD_CODE, PADD_NAME,
       AVG_TEMP_F, HEATING_DEGREE_DAYS, COOLING_DEGREE_DAYS
FROM APERTURE_DB.ENERGY.MART_WEATHER
WHERE PADD_ID IN (1, 2)
  AND MONTH_NUM IN (11, 12, 1, 2, 3)
  AND OBSERVATION_DATE >= DATEADD(YEAR, -1, CURRENT_DATE())
ORDER BY OBSERVATION_DATE DESC
LIMIT 500;

-- 3.4  Geopolitical tension by country (top 10 most active)
SELECT COUNTRY_CODE, COUNTRY_NAME, ENERGY_RELEVANCE, PRIMARY_PADD_IMPACT,
       COUNT(*) AS WEEKS_OBSERVED,
       ROUND(AVG(GEOPOLITICAL_TENSION_SCORE), 2) AS AVG_TENSION,
       SUM(CONFLICT_EVENT_COUNT) AS TOTAL_CONFLICTS,
       SUM(COOPERATION_EVENT_COUNT) AS TOTAL_COOPERATION
FROM APERTURE_DB.ENERGY.MART_GEOPOLITICAL
WHERE EVENT_DATE >= DATEADD(YEAR, -1, CURRENT_DATE())
GROUP BY COUNTRY_CODE, COUNTRY_NAME, ENERGY_RELEVANCE, PRIMARY_PADD_IMPACT
ORDER BY AVG_TENSION DESC
LIMIT 10;

-- 3.5  STEO Forecast trend (last 2 years)
SELECT FORECAST_MONTH, MONTH_NAME, YEAR_NUM,
       STEO_WTI_FORECAST, STEO_BRENT_FORECAST,
       STEO_PRODUCTION_FORECAST, STEO_CONSUMPTION_FORECAST
FROM APERTURE_DB.ENERGY.MART_EIA_STEO
WHERE FORECAST_MONTH >= DATEADD(YEAR, -2, CURRENT_DATE())
ORDER BY FORECAST_MONTH DESC;

-- 3.6  Row counts per mart (sanity check — rows should equal distinct keys)
SELECT 'MART_EIA_PRICES' AS MART, COUNT(*) AS TOTAL_ROWS
FROM APERTURE_DB.ENERGY.MART_EIA_PRICES
UNION ALL
SELECT 'MART_EIA_INVENTORY', COUNT(*)
FROM APERTURE_DB.ENERGY.MART_EIA_INVENTORY
UNION ALL
SELECT 'MART_EIA_STEO', COUNT(*)
FROM APERTURE_DB.ENERGY.MART_EIA_STEO
UNION ALL
SELECT 'MART_WEATHER', COUNT(*)
FROM APERTURE_DB.ENERGY.MART_WEATHER
UNION ALL
SELECT 'MART_GEOPOLITICAL', COUNT(*)
FROM APERTURE_DB.ENERGY.MART_GEOPOLITICAL
ORDER BY MART;


-- =============================================================================
-- SECTION 4: PIPELINE MONITORING QUERIES
-- =============================================================================

-- 4.1  Pipeline log — latest runs per procedure
SELECT
    PROCEDURE_NAME,
    MAX(RUN_STARTED_AT) AS LAST_RUN,
    MAX(CASE WHEN STATUS = 'SUCCESS' THEN RUN_STARTED_AT END) AS LAST_SUCCESS,
    MAX(CASE WHEN STATUS = 'ERROR' THEN RUN_STARTED_AT END) AS LAST_ERROR,
    COUNT(*) AS TOTAL_RUNS,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN STATUS = 'ERROR' THEN 1 ELSE 0 END) AS ERROR_COUNT,
    SUM(CASE WHEN STATUS = 'SKIPPED' THEN 1 ELSE 0 END) AS SKIPPED_COUNT
FROM APERTURE_DB.ENERGY.PIPELINE_LOG
GROUP BY PROCEDURE_NAME
ORDER BY LAST_RUN DESC;

-- 4.2  Pipeline log — recent errors (last 7 days)
SELECT PROCEDURE_NAME, RUN_STARTED_AT, STATUS, ROWS_AFFECTED, ERROR_MESSAGE
FROM APERTURE_DB.ENERGY.PIPELINE_LOG
WHERE STATUS = 'ERROR'
  AND RUN_STARTED_AT >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
ORDER BY RUN_STARTED_AT DESC
LIMIT 50;

-- 4.3  Pipeline log — full history (last 30 days)
SELECT PROCEDURE_NAME, RUN_STARTED_AT, RUN_ENDED_AT, STATUS,
       ROWS_AFFECTED,
       DATEDIFF(SECOND, RUN_STARTED_AT, RUN_ENDED_AT) AS DURATION_SECONDS,
       ERROR_MESSAGE
FROM APERTURE_DB.ENERGY.PIPELINE_LOG
WHERE RUN_STARTED_AT >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
ORDER BY RUN_STARTED_AT DESC;

-- 4.4  Data freshness check — how current is each source?
SELECT
    'EIA Prices' AS SOURCE,
    MAX(PRICE_DATE) AS LATEST_DATE,
    DATEDIFF(DAY, MAX(PRICE_DATE), CURRENT_DATE()) AS DAYS_STALE
FROM APERTURE_DB.ENERGY.FACT_EIA_PRICES
UNION ALL
SELECT 'EIA Inventory', MAX(REPORT_DATE), DATEDIFF(DAY, MAX(REPORT_DATE), CURRENT_DATE())
FROM APERTURE_DB.ENERGY.FACT_EIA_INVENTORY
UNION ALL
SELECT 'NOAA Weather', MAX(OBSERVATION_DATE), DATEDIFF(DAY, MAX(OBSERVATION_DATE), CURRENT_DATE())
FROM APERTURE_DB.ENERGY.FACT_NOAA_WEATHER
UNION ALL
SELECT 'GDELT Events', MAX(EVENT_DATE), DATEDIFF(DAY, MAX(EVENT_DATE), CURRENT_DATE())
FROM APERTURE_DB.ENERGY.FACT_GDELT_EVENTS
UNION ALL
SELECT 'EIA STEO', MAX(FORECAST_MONTH), DATEDIFF(DAY, MAX(FORECAST_MONTH), CURRENT_DATE())
FROM APERTURE_DB.ENERGY.FACT_EIA_STEO_FORECASTS;

-- 4.5  Task status check
SHOW TASKS IN SCHEMA APERTURE_DB.ENERGY;

-- =============================================================================
-- NOTES
-- =============================================================================
-- Before running Section 2+ queries, you must:
--   1. Set real API keys:
--      ALTER SECRET APERTURE_DB.ENERGY.EIA_API_KEY SET SECRET_STRING = '<your-eia-key>';
--      ALTER SECRET APERTURE_DB.ENERGY.NOAA_CDO_TOKEN SET SECRET_STRING = '<your-noaa-token>';
--   2. Run backfill procedures:
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_EIA_PRICES();
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_EIA_RETAIL_PRICES();
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_EIA_INVENTORY();
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_NOAA_WEATHER();
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_GDELT_EVENTS();
--      CALL APERTURE_DB.ENERGY.SP_BACKFILL_EIA_STEO();
--   3. Resume tasks for ongoing refresh:
--      ALTER TASK APERTURE_DB.ENERGY.TASK_DAILY_EIA_PRICES RESUME;
--      ALTER TASK APERTURE_DB.ENERGY.TASK_DAILY_NOAA_WEATHER RESUME;
--      ALTER TASK APERTURE_DB.ENERGY.TASK_WEEKLY_EIA_INVENTORY RESUME;
--      ALTER TASK APERTURE_DB.ENERGY.TASK_WEEKLY_GDELT_EVENTS RESUME;
--      ALTER TASK APERTURE_DB.ENERGY.TASK_MONTHLY_EIA_STEO RESUME;
--      ALTER TASK APERTURE_DB.ENERGY.TASK_WEEKLY_EIA_RETAIL_PRICES RESUME;
-- =============================================================================
